[project]
name = "project_1_350"
description = PostgreSQL database about the world,
especially economic data.

Provides not only a design, but actual data (real and some
possibly fake) and schema objects like functions and procedures.